---
- hosts: localhost
  handlers:
    - name: Restart macOS Finder
      command: killall Finder
      listen: "restart finder"
    - name: Restart macOS Dock
      command: killall Dock
      listen: "restart dock"

# ----------------------------------------------------------------------------------------------------------------------

  vars:
    yubikey:
      gpgKey: "08FDB44B6D6320215D1EE8C13025FFE233CCC24B"
      gpg: true
      ssh: true

    git:
      fullName: "Claudio Dekker"
      email: "claudio@laravel.com"
      signingKey: "{{ yubikey.gpgKey }}"

    # Applications that have an ID are AppStore apps, the names are just for display/identification.
    # Applications that don't have an ID are Homebrew Casks. In this case, the names are the to-be-installed formulas.
    applications:
      - { id: 1497506650, name: Yubico Authenticator }
      - { id: 747648890, name: Telegram }
      - { id: 803453959, name: Slack }
      - { name: 1password }
      - { name: cleanshot }
      - { name: firefox }
      - { name: fork }
      - { name: little-snitch }
      - { name: linear-linear }
      - { name: obsidian }
      - { name: phpstorm }
      - { name: protonvpn }
      - { name: responsively }
      - { name: sublime-text }
      - { name: "stripe/stripe-cli/stripe", cask: false }
      - { name: tableplus }
      - { name: tuple }

    utilities:
      - { name: z }
      - { name: zx }

    macOS:
      autocorrect: false
      clearBottomRightHotCorner: true
      disableSearchManPageIndexInTerminalShortcut: true
      disableMouseAcceleration: true
      dockRecentApps: false
      showAllFiles: true
      smartQuotes: false

    terminal:
      theme: Pro
    
    ghostty:
      tmux: true
      
    gitignore:
      - .DS_Store
      - .idea/

    composer:
      - "laravel/pint ^1.19"

  roles:
    - fact-gatherer
    - fonts
    - tmux
    - ghostty
    - oh-my-zsh
    - yubikey

  tasks:
    - include_tasks: tasks/applications.yml
      tags: applications
    - include_tasks: tasks/git.yml
      tags: git
    - include_tasks: tasks/macOS.yml
      tags: macOS
    - include_tasks: tasks/php.yml
      tags: php
    - include_tasks: tasks/terminal.yml
      tags: terminal
    - include_tasks: tasks/utilities.yml
      tags: utilities
