---
- name: Set up our User Preferences
  copy:
    src: User
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages"

- name: Add our Packages to Sublime Text
  copy:
    src: "Installed Packages"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3"

- name: Ensure Composer (PHP) is installed. # Needed for the next task..
  homebrew:
    name: 'composer'
    state: latest

- name: Install dependencies of SublimeLinter-php
  composer:
    command: require
    global_command: yes
    arguments: '{{ item }}'
  with_items:
    - 'squizlabs/php_codesniffer=*'
    - 'phpmd/phpmd'
    - 'friendsofphp/php-cs-fixer'

- name: Copy the default .php_cs info to the HOME dir.
  copy:
    src: .php_cs
    dest: "{{ ansible_env.HOME }}/.php_cs"

- name: Configure SublimePhpCsFixer.sublime-settings
  template:
    src: SublimePhpCsFixer.sublime-settings.j2
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages/User/SublimePhpCsFixer.sublime-settings"

