---
- name: Install tmux
  homebrew:
    name: 'tmux'
    state: latest
  register: tmux_installation

- name: Ensure our tmux configuration is present
  copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
  register: tmux_configuration
  when: tmux_installation is changed

- name: Install 'reattach-to-user-namespace'
  homebrew:
    name: 'reattach-to-user-namespace'
    state: latest
