---
- name: Ensure 'mas' is installed (Mac App Store CLI tool)
  homebrew:
    name: 'mas'
    state: latest
  when: ('mas' not in brew_formulae_list) or (not last_ran_within_last_day|default(false))

- name: Gather installed applications (Mac App Store)
  command: mas list
  register: mas_installed_apps
  changed_when: false

- name: Upgrade all outdated macOS Applications (Mac App Store)
  command: mas upgrade
  when: not last_ran_within_last_day|default(false)

- name: Install macOS Applications (Mac App Store)
  command: mas install "{{ item.id }}"
  register: install_macos_applications
  loop: "{{ applications|default([]) }}"
  changed_when: install_macos_applications.stderr.find(' is already installed') == -1
  when: (item.id is defined) and (item.name is defined) and (item.id|string not in mas_installed_apps.stdout_lines)

- name: Ensure macOS Applications (Homebrew - Cask)
  homebrew_cask:
    name: '{{ item.name }}'
    state: 'latest'
  with_items: "{{ applications|default([]) }}"
  when: (item.id is not defined) and (item.name is defined) and (item.cask|default(true)) and ((item.name not in brew_cask_list) or (not last_ran_within_last_day|default(false)))

- name: Ensure macOS Applications (Homebrew - Regular)
  homebrew:
    name: '{{ item.name }}'
    state: 'latest'
  with_items: "{{ applications|default([]) }}"
  when: (item.id is not defined) and (item.name is defined) and (not item.cask|default(true)) and ((item.name not in brew_cask_list) or (not last_ran_within_last_day|default(false)))
