---
- name: Toggle macOS Autocorrect
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: boolean
    value: "{{ (macOS|default({})).autocorrect|default(true) }}"
    state: present

- name: Toggle macOS "Smart Quotes"
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item }}"
    type: boolean
    value: "{{ (macOS|default({})).smartQuotes|default(true) }}"
    state: present
  with_items:
    - "NSAutomaticQuoteSubstitutionEnabled"
    - "NSAutomaticDashSubstitutionEnabled" # Automatically toggled by macOS as well when disabling smart quotes.

- name: Show all Files in Finder
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: boolean
    value: "{{ (macOS|default({})).showAllFiles|default(false) }}"
    state: present
  notify:
    - restart finder

- name: Toggle Recent Apps (Dock)
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: boolean
    value: "{{ (macOS|default({})).dockRecentApps|default(true) }}"
    state: present
  register: show_recents_toggled

- name: Clear bottom-right "Hot Corner"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: integer
    value: 1
    state: present
  register: hot_corners_clear_bottom_right
  when: (macOS|default({})).clearBottomRightHotCorner|default(false)

- name: Housekeeping for Recent Apps (Dock)
  command: "defaults write com.apple.dock recent-apps {}"
  when: (show_recents_toggled is changed) or (hot_corners_clear_bottom_right is changed)
  notify:
    - restart dock

- name: Determine status of macOS CMD+Shift+A "Search man Page Index in Terminal" built-in
  command: "plutil -extract NSServicesStatus json -o - {{ ansible_env.HOME }}/Library/Preferences/pbs.plist"
  register: command_shift_a_builtin
  changed_when: false
  failed_when: (command_shift_a_builtin.rc == 1) and ('"No value at that key path or invalid key path" not in command_shift_a_builtin.stdout')

- name: Disable macOS CMD+Shift+A "Search man Page Index in Terminal" built-in
  command: "plutil -replace NSServicesStatus -json \"{ \\\"com.apple.Terminal - Search man Page Index in Terminal - searchManPages\\\": { \\\"enabled_context_menu\\\": 0, \\\"enabled_services_menu\\\": 0, \\\"presentation_modes\\\": { \\\"ContextMenu\\\": 0, \\\"ServicesMenu\\\": 0 } } }\" {{ ansible_env.HOME }}/Library/Preferences/pbs.plist"
  when: ("searchManPages" not in command_shift_a_builtin.stdout) and (macOS|default({})).disableSearchManPageIndexInTerminalShortcut|default(false)

- name: Re-enable macOS CMD+Shift+A "Search man Page Index in Terminal" built-in
  command: "plutil -replace NSServicesStatus -json \"{ }\" {{ ansible_env.HOME }}/Library/Preferences/pbs.plist"
  when: ("searchManPages" in command_shift_a_builtin.stdout) and ((macOS|default({})).disableSearchManPageIndexInTerminalShortcut is defined) and not macOS.disableSearchManPageIndexInTerminalShortcut
