---
- name: Install NodeJS
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodenv
    - node-build
  when: (item not in brew_formulae_list) or (not last_ran_within_last_day|default(false))
  register: nodejs_installed

- name: Add nodenv to our .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    create: yes
    line: 'eval "$(nodenv init -)"'
    state: present
  when: nodejs_installed is changed

- name: Install the required NodeJS version
  command: "nodenv install {{ nodejs|default('8.11.3') }} -s"
  register: nodejs_installed_version
  changed_when: "nodejs_installed_version.stderr.find('Installed ') != -1"

- name: Change the global/default NodeJS version
  shell: |
    nodenv global
    nodenv global {{ nodejs|default('8.11.3') }}
    nodenv global
  register: nodejs_current_version
  changed_when: "nodejs_current_version.stdout_lines.0 != nodejs_current_version.stdout_lines.1"
