---
- name: Install Laravel Herd
  homebrew_cask:
    name: 'herd'
    state: latest
  when: ('herd' not in brew_cask_list) or (not last_ran_within_last_day|default(false))

- name: Install Global Composer Packages
  ansible.builtin.command: composer global require '{{ item }}' -W
  with_items: "{{ composer|default([]) }}"
  register: composer_packages
  changed_when: "'Nothing to install, update or remove' not in composer_packages.stderr"

- name: Ensure composer global binaries are in PATH
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.composer/vendor/bin:$PATH"'
    state: present
  when: composer_packages is changed
