---
- name: Ensure all repositories are tapped (Homebrew)
  homebrew_tap:
    name: '{{ item.tap }}'
    state: '{{ "absent" if item.removed|default(false) else "present" }}'
  with_items: "{{ utilities|default([]) }}"
  when: item.tap is defined

- name: Ensure macOS Utilities (Homebrew)
  homebrew:
    name: '{{ item.name }}'
    state: '{{ "absent" if item.removed|default(false) else "latest" }}'
    install_options: '{{ "zap" if item.remove|default(false) else "" }}'
  with_items: "{{ utilities|default([]) }}"
  when: (item.name is defined) and ((item.name not in brew_formulae_list) or (not last_ran_within_last_day|default(false)))
