---
- name: Uninstall NodeJS
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items:
    - nodenv
    - node-build
  register: nodejs_removed

- name: Remove nodenv from our .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    create: yes
    line: 'eval "$(nodenv init -)"'
    state: absent
  when: nodejs_removed is changed
